[package]
name = "alp-test"
version = "0.1.0"
edition = "2024"

[dependencies]
alp = { git = "https://github.com/spiraldb/alp" }
arrow = "53.0"
bytes = "1.5"
rand = "0.8"

[dev-dependencies]
criterion = "0.5"
